backend:
  name: github
  repo: hugojavierpino/javierpino
  branch: main
  base_url: https://javierpino-auth.hugojavier95.workers.dev
  auth_endpoint: /auth

media_folder: public/images
public_folder: /images